package interfaces

import (
	"context"
)

// DraftSet represents a set of drafts generated by the LLM
type DraftSet struct {
	Posts    []string
	Articles []string
}

// LLMService defines the contract for LLM-based content generation
type LLMService interface {
	// SendRequest sends a raw prompt to the LLM and returns the response
	SendRequest(ctx context.Context, prompt string) (string, error)

	// GenerateIdeas generates content ideas based on a topic
	// Returns a list of ideas or an error
	GenerateIdeas(ctx context.Context, topic string, count int) ([]string, error)

	// GenerateDrafts generates multiple draft contents (posts and articles)
	// based on an idea and user context
	GenerateDrafts(ctx context.Context, idea string, userContext string) (DraftSet, error)

	// RefineDraft refines an existing draft based on user feedback
	// with optional conversation history for context
	RefineDraft(ctx context.Context, draft string, userPrompt string, history []string) (string, error)
}
